### ISSUE TITLE
 [CICD] - add PR title validation

### ISSUE THREAD

**Issue by tiagomichaelsousa** [comoser/baby-food-intro-api#38]
### Implementation PR

NA

### Reference Issues

N/A

### Summary

- Create `.github/workflows/pr-title-checker.yaml`
- Trigger the validation when:
  - opened
  - reopened
  - edited
  - synchronize

### Basic Example

```yaml
steps:
  - uses: aslafy-z/conventional-pr-title-action@v2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Drawbacks

N/A
