### ISSUE TITLE
 [CICD] - add label validation

### ISSUE THREAD

**Issue by tiagomichaelsousa** [comoser/baby-food-intro-api#40]
### Summary

- Create .github/workflows/label-checker.yaml

### Basic Example

Validate both semver and conventional commits labels in order to be used in the future with release drafter

```yaml
steps:
      - name: Check for Semver labels
        uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

### Drawbacks

N/A
